// The Command Center console's Chat view: a Claude Code transcript made into messages (server/convo/
// transcript.ts), read a bounded piece at a time as it grows (tail.ts), the rows the page draws from
// them (ui/pm/chat/logic.ts), the terminal's plain text for workers with no transcript, and the
// Chat | Terminal setting (ui/pm/chat/pref.ts).
import test from 'node:test';
import assert from 'node:assert/strict';
import { appendFileSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { PREVIEW_CHARS, TranscriptReader, toolSummary } from '../src/server/convo/transcript.js';
import { TranscriptTail } from '../src/server/convo/tail.js';
import { chatItems, screenText, stripAnsi, upsert } from '../src/client/ui/pm/chat/logic.js';
import { PMC_VIEW_KEY, onPmcView, savePmcView, savedPmcView } from '../src/client/ui/pm/chat/pref.js';
import type { ConvoMsg } from '../src/shared/protocol.js';

const T = '2026-10-05T05:37:46.669Z';
const base = { isSidechain: false, sessionId: 's1', cwd: '/work', userType: 'external', timestamp: T };
const user = (uuid: string, content: unknown, extra: object = {}) => ({ ...base, type: 'user', uuid, message: { role: 'user', content }, ...extra });
const assistant = (uuid: string, id: string, content: unknown[]) => ({ ...base, type: 'assistant', uuid, message: { id, type: 'message', role: 'assistant', model: 'claude-opus-5-5', content } });
const result = (uuid: string, toolUseId: string, content: unknown, isError = false) => user(uuid, [{ type: 'tool_result', tool_use_id: toolUseId, content, is_error: isError }]);
const jsonl = (lines: unknown[]) => lines.map((l) => JSON.stringify(l)).join('\n') + '\n';

/** A short session, shaped like a real one: bookkeeping lines, a prompt, thinking, text and tools over several lines, a subagent's sidechain, a question. */
const SESSION = [
  { type: 'permission-mode', permissionMode: 'auto', sessionId: 's1' },
  { type: 'file-history-snapshot', messageId: 'm0', snapshot: {} },
  { ...base, type: 'attachment', uuid: 'att', attachment: { type: 'hook_success', hookName: 'SessionStart:startup', stdout: 'ok' } },
  user('u1', 'Give me a short **status** update.'),
  user('meta', 'Caveat: the messages below were generated by the user', { isMeta: true }),
  user('cmd', '<command-name>/clear</command-name>'),
  assistant('a1', 'msg_1', [{ type: 'thinking', thinking: 'hidden musing', signature: 'x' }]),
  assistant('a2', 'msg_1', [{ type: 'text', text: 'Checking the board first.' }]),
  assistant('a3', 'msg_1', [{ type: 'tool_use', id: 'tu_bash', name: 'Bash', input: { command: 'mxcli check', description: 'Check the model' } }]),
  result('r1', 'tu_bash', 'All checks passed'),
  assistant('a4', 'msg_2', [{ type: 'tool_use', id: 'tu_read', name: 'Read', input: { file_path: '/work/docs/plan.md' } }]),
  result('r2', 'tu_read', [{ type: 'text', text: 'PRIVATE FILE CONTENTS' }]),
  assistant('a5', 'msg_3', [{ type: 'tool_use', id: 'tu_e1', name: 'Edit', input: { file_path: '/work/src/a.ts', old_string: 'x', new_string: 'y' } }]),
  result('r3', 'tu_e1', 'ok'),
  assistant('a6', 'msg_4', [{ type: 'tool_use', id: 'tu_e2', name: 'Edit', input: { file_path: '/work/src/b.ts' } }]),
  result('r4', 'tu_e2', 'ok'),
  assistant('a7', 'msg_5', [{ type: 'tool_use', id: 'tu_e3', name: 'Write', input: { file_path: '/work/src/c.ts', content: 'export {}' } }]),
  result('r5', 'tu_e3', 'File too large: '.padEnd(400, 'x'), true),
  { ...assistant('side', 'msg_side', [{ type: 'text', text: 'a subagent talking' }]), isSidechain: true },
  assistant('a8', 'msg_6', [
    { type: 'text', text: 'Two things:\n\n- one\n- two' },
    { type: 'tool_use', id: 'tu_ask', name: 'AskUserQuestion', input: { questions: [{ question: 'Merge PR #12 now?', header: 'Merge', options: [{ label: 'Yes', description: 'merge it' }, { label: 'No' }], multiSelect: false }] } },
  ]),
  { type: 'cost-state', totalCostUSD: 1.2 },
];

test('a transcript becomes the conversation: prompts, replies, tool rows and the question, nothing else', () => {
  const r = new TranscriptReader();
  r.feed(jsonl(SESSION));
  assert.deepEqual(
    r.messages.map((m) => m.kind),
    ['user', 'agent', 'tool', 'tool', 'tool', 'tool', 'tool', 'agent', 'ask'],
  );
  const [u, a1, bash, read, , , write, a2, ask] = r.messages as any[];
  assert.equal(u.text, 'Give me a short **status** update.');
  assert.equal(u.at, Date.parse(T));
  assert.equal(a1.text, 'Checking the board first.');
  assert.deepEqual([bash.summary, bash.status, bash.preview], ['Ran mxcli check', 'ok', undefined]);
  // A file's contents never leave the office, not even as a preview.
  assert.equal(read.summary, 'Read plan.md');
  assert.equal(read.preview, undefined);
  const all = JSON.stringify(r.messages);
  assert.ok(!all.includes('PRIVATE FILE'));
  assert.ok(!all.includes('hidden musing'), 'no thinking');
  assert.ok(!all.includes('subagent talking'), 'no sidechain');
  assert.equal(write.status, 'error');
  assert.ok(write.preview.length <= PREVIEW_CHARS);
  assert.equal(a2.text, 'Two things:\n\n- one\n- two');
  assert.deepEqual([ask.question, ask.options, ask.answered], ['Merge PR #12 now?', ['Yes', 'No'], false]);
});

test('one reply over several lines is one message, and a result coming in changes its tool row', () => {
  const r = new TranscriptReader();
  r.feed(jsonl([assistant('a', 'msg_x', [{ type: 'text', text: 'First.' }]), assistant('b', 'msg_x', [{ type: 'text', text: 'Second.' }])]));
  assert.equal(r.messages.length, 1);
  assert.equal((r.messages[0] as any).text, 'First.\n\nSecond.');
  const started = r.feed(jsonl([assistant('c', 'msg_y', [{ type: 'tool_use', id: 't1', name: 'Bash', input: { command: 'npm test' } }])]));
  assert.deepEqual(
    started.map((m) => [m.kind, (m as any).status]),
    [['tool', 'running']],
  );
  const done = r.feed(jsonl([result('d', 't1', 'boom', true)]));
  assert.deepEqual(
    done.map((m) => [m.id, (m as any).status, (m as any).preview]),
    [['t1', 'error', 'boom']],
  );
  // An answer to the question marks it answered.
  r.feed(jsonl([assistant('e', 'msg_z', [{ type: 'tool_use', id: 'q1', name: 'AskUserQuestion', input: { questions: [{ question: 'Go?', options: ['a'] }] } }])]));
  const answered = r.feed(jsonl([result('f', 'q1', 'User answered: a')]));
  assert.equal((answered[0] as any).answered, true);
});

test('a line cut off mid-way waits for the rest', () => {
  const r = new TranscriptReader();
  const line = JSON.stringify(user('u', 'hello there'));
  assert.deepEqual(r.feed(line.slice(0, 20)), []);
  assert.equal(r.feed(line.slice(20) + '\n').length, 1);
});

test('tool calls in a few words', () => {
  assert.equal(toolSummary('Bash', { command: 'git log --oneline -3' }).summary, 'Ran git log --oneline -3');
  assert.equal(toolSummary('Bash', { command: 'x'.repeat(200), description: 'Build everything' }).summary, 'Build everything');
  assert.equal(toolSummary('Edit', { file_path: 'C:\\w\\src\\main.ts' }).summary, 'Edited main.ts');
  assert.equal(toolSummary('Grep', { pattern: 'TODO' }).summary, 'Searched for TODO');
  assert.equal(toolSummary('mcp__office__list_workers', {}).summary, 'Used office list_workers');
});

test('the tail reads only the end of a long transcript, then only what was added, by offset', () => {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'convo-'));
  try {
    const file = path.join(dir, 's.jsonl');
    const filler = jsonl(Array.from({ length: 200 }, (_, i) => user(`old${i}`, `old prompt ${i} `.padEnd(200, '.'))));
    writeFileSync(file, filler + jsonl([user('new1', 'the latest')]));
    const tail = new TranscriptTail(file, 4096, 4096);
    const first = tail.read()!;
    assert.equal(first.reset, true);
    const texts = tail.reader.messages.map((m) => (m as any).text as string);
    assert.ok(texts.length < 30, `only the tail was read (${texts.length})`);
    assert.equal(texts[texts.length - 1], 'the latest');
    assert.ok(
      texts.every((t) => t === 'the latest' || t.startsWith('old prompt')),
      'no half line from where it started',
    );
    const at = tail.offset!;
    assert.deepEqual(tail.read()!.messages, []);
    // Half a line, then the rest: nothing until it's whole.
    const line = jsonl([user('new2', 'and another')]);
    appendFileSync(file, line.slice(0, 10));
    assert.deepEqual(tail.read()!.messages, []);
    assert.equal(tail.offset, at);
    appendFileSync(file, line.slice(10));
    const next = tail.read()!;
    assert.equal(next.reset, false);
    assert.deepEqual(
      next.messages.map((m) => (m as any).text),
      ['and another'],
    );
    // Written over with something shorter: read again from the start.
    writeFileSync(file, jsonl([user('fresh', 'a new session')]));
    const again = tail.read()!;
    assert.equal(again.reset, true);
    assert.deepEqual(
      tail.reader.messages.map((m) => (m as any).text),
      ['a new session'],
    );
    // A line longer than a whole read is skipped rather than waited on forever.
    appendFileSync(file, jsonl([user('huge', 'y'.repeat(10_000)), user('after', 'after the huge one')]));
    for (let i = 0; i < 5; i++) tail.read();
    assert.equal((tail.reader.messages.at(-1) as any).text, 'after the huge one');
    assert.equal(new TranscriptTail(path.join(dir, 'missing.jsonl')).read(), undefined);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

const tool = (id: string, toolName: string, target: string, status: 'ok' | 'error' | 'running' = 'ok'): ConvoMsg => ({ id, kind: 'tool', tool: toolName, summary: `${toolName} ${target}`, target, status });

test('runs of edits, reads and searches fold into one row; other tools stay a row each', () => {
  const items = chatItems([
    { id: 'u', kind: 'user', text: 'go' },
    tool('1', 'Edit', 'a.ts'),
    tool('2', 'MultiEdit', 'b.ts'),
    tool('3', 'Write', 'c.ts'),
    tool('4', 'Edit', 'd.ts', 'error'),
    tool('5', 'Edit', 'd.ts', 'running'),
    tool('6', 'Bash', 'npm test'),
    tool('7', 'Bash', 'npm run build'),
    tool('8', 'Read', 'x.ts'),
    tool('9', 'Read', 'x.ts'),
  ]);
  assert.deepEqual(
    items.map((i) => (i.kind === 'tools' ? [i.label, i.status, i.tools.length] : i.msg.kind)),
    ['user', ['Edited 2 files', 'ok', 2], ['Write c.ts', 'ok', 1], ['Edit d.ts', 'error', 2], ['Bash npm test', 'ok', 1], ['Bash npm run build', 'ok', 1], ['Read x.ts', 'ok', 2]],
  );
});

test('an update replaces messages by id and adds new ones, keeping the newest', () => {
  const a: ConvoMsg = { id: 'a', kind: 'user', text: 'one' };
  const b: ConvoMsg = { id: 'b', kind: 'agent', text: 'two' };
  const list = upsert([a, b], [{ ...b, text: 'two, longer' }, { id: 'c', kind: 'user', text: 'three' }]);
  assert.deepEqual(
    list.map((m) => (m as any).text),
    ['one', 'two, longer', 'three'],
  );
  assert.deepEqual(
    upsert(list, [], 2).map((m) => m.id),
    ['b', 'c'],
  );
});

test("the fallback: the terminal's text without its escapes", () => {
  assert.equal(stripAnsi('\x1b[1;32m✓ passed\x1b[0m \x1b]0;title\x07done\x1b(B'), '✓ passed done');
  assert.equal(stripAnsi('a\x1b[2K\x1b[1Gb\x07c'), 'abc');
  assert.equal(screenText(['', '\x1b[31m$ npm test\x1b[0m   ', '', '', '', 'ok\r', '', '']), '$ npm test\n\nok');
  assert.equal(screenText([]), '');
});

test('the Chat | Terminal setting: Chat by default, kept in this browser, told to whoever follows it', () => {
  const g = globalThis as { localStorage?: unknown };
  const had = g.localStorage;
  try {
    const kept = new Map<string, string>();
    g.localStorage = { getItem: (k: string) => kept.get(k) ?? null, setItem: (k: string, v: string) => void kept.set(k, v) };
    assert.equal(savedPmcView(), 'chat');
    const heard: string[] = [];
    const off = onPmcView((v) => heard.push(v));
    savePmcView('terminal');
    assert.equal(kept.get(PMC_VIEW_KEY), 'terminal');
    assert.equal(savedPmcView(), 'terminal');
    assert.deepEqual(heard, ['terminal']);
    off();
    kept.set(PMC_VIEW_KEY, 'nonsense');
    assert.equal(savedPmcView(), 'chat');
    // Blocked storage: Chat, and picking still works for this visit.
    const blocked = () => {
      throw new Error('blocked');
    };
    g.localStorage = { getItem: blocked, setItem: blocked };
    assert.equal(savedPmcView(), 'chat');
    assert.doesNotThrow(() => savePmcView('terminal'));
  } finally {
    g.localStorage = had;
  }
});
