// One card per credential on 🔌 Connections: its status, where the value in use comes from (never the
// value: a masked tail), its last Test, Test / Replace / Remove, and what it's for and how to make one.
import { CREDENTIAL_META, type ConnectionsView, type CredentialStatus, type CredentialView } from '../../../shared/connections';
import { h, timeAgo } from '../dom';
import { connectionsApi } from './api';

/** Runs a change and redraws the page with the office's answer (or shows its error). */
export type Run = (what: () => Promise<ConnectionsView>, done?: string) => Promise<void>;

const STATUS: Record<CredentialStatus, string> = { connected: '✅ Connected', missing: '➖ Missing', invalid: '⛔ Invalid', expiring: '⏳ Expiring' };

const SOURCE: Record<NonNullable<CredentialView['source']>, string> = {
  connections: 'Saved here',
  env: 'From an environment variable',
  file: 'From a file',
  generated: 'Generated by the office',
};

function where(v: CredentialView): string {
  if (!v.source) return 'Not set anywhere.';
  const bits = [SOURCE[v.source]];
  if (v.where) bits.push(v.where);
  if (v.tail) bits.push(v.tail);
  if (v.savedAt) bits.push(`saved by ${v.savedBy ?? 'someone'} ${timeAgo(v.savedAt)}`);
  return bits.join(' · ');
}

/** The form that takes a new value: a password field (or two, for the office password) and Save. */
function valueForm(v: CredentialView, run: Run, cancel: () => void): HTMLElement {
  const meta = CREDENTIAL_META[v.id];
  const pw = v.id === 'password';
  const input = h('input', { type: 'password', autocomplete: 'new-password', spellcheck: 'false', placeholder: pw ? 'New office password' : 'Paste the token', 'aria-label': pw ? 'New office password' : `${meta.label}` }) as HTMLInputElement;
  const again = pw ? (h('input', { type: 'password', autocomplete: 'new-password', placeholder: 'The same again', 'aria-label': 'New office password again' }) as HTMLInputElement) : undefined;
  const err = h('p.cx-err');
  const save = h('button.btn.primary', { type: 'button' }, pw ? 'Change password' : 'Save');
  const go = () => {
    const value = input.value;
    if (!value.trim()) return input.focus();
    if (again && again.value !== value) {
      err.textContent = 'The two don’t match';
      return again.focus();
    }
    save.disabled = true;
    input.value = '';
    if (again) again.value = '';
    void run(() => connectionsApi.save(v.id, value), pw ? 'Password changed' : `${meta.label} saved`).finally(() => (save.disabled = false));
  };
  save.addEventListener('click', go);
  for (const i of [input, again]) i?.addEventListener('keydown', (e) => e.key === 'Enter' && go());
  setTimeout(() => input.focus(), 20);
  return h(
    'div.cx-form',
    {},
    input,
    again ?? null,
    h('div.cx-actions', {}, save, h('button.btn', { type: 'button', onclick: cancel }, 'Cancel')),
    err,
    h('p.cx-note', {}, pw ? 'Only a hash is kept. Everyone on the shared password is signed out; you stay signed in.' : 'It goes to the office once and is stored encrypted. It’s never shown again, only its last characters.'),
  );
}

function help(v: CredentialView, org: string): HTMLElement {
  const meta = CREDENTIAL_META[v.id];
  const url = meta.createUrl?.(org);
  return h(
    'details.cx-help',
    { open: v.status === 'missing' },
    h('summary', {}, 'What it’s for and how to make one'),
    h('p', {}, meta.purpose),
    h('p.cx-sub', {}, 'Give it exactly:'),
    h('ul', {}, ...meta.scopes.map((s) => h('li', {}, s))),
    h('ol', {}, ...meta.how.map((s) => h('li', {}, s))),
    url ? h('a.btn.cx-link', { href: url, target: '_blank', rel: 'noopener noreferrer' }, `${meta.createLabel ?? 'Create one'} ↗`) : null,
  );
}

function lastTest(v: CredentialView): HTMLElement | null {
  const c = v.check;
  if (!c) return v.source && CREDENTIAL_META[v.id].testable ? h('p.cx-note', {}, 'Not tested yet.') : null;
  const repos = c.repos?.length ? h('p.cx-repos', {}, `Repositories: ${c.repos.join(', ')}${(c.repoCount ?? 0) > c.repos.length ? ` and ${(c.repoCount ?? 0) - c.repos.length} more` : ''}${c.owners?.length ? ` · owners: ${c.owners.join(', ')}` : ''}`) : null;
  return h('div.cx-test', {}, h('p', {}, h('b', {}, `Tested ${timeAgo(c.at)}: `), c.summary), repos, ...(c.details ?? []).map((d) => h('p.cx-note', {}, d)));
}

/** The Mendix card's own extra: which floors' agents get the token. */
function mendixFloors(view: ConnectionsView, run: Run): HTMLElement | null {
  if (!view.mendixFloors.length) return null;
  return h(
    'div.cx-floors',
    {},
    h('p.cx-sub', {}, 'Give agents the Mendix token (MENDIX_TOKEN / MX_PAT), per project. Off by default; workers hired after the change get it:'),
    ...view.mendixFloors.map((f) => {
      const box = h('input', { type: 'checkbox', checked: f.on }) as HTMLInputElement;
      box.addEventListener('change', () => void run(() => connectionsApi.mendixFloor(f.id, box.checked), `${f.name}: ${box.checked ? 'agents get the Mendix token' : 'no Mendix token for agents'}`));
      return h('label.cx-check', { title: f.dir }, box, ` ${f.name}`);
    }),
  );
}

export function credentialCard(v: CredentialView, view: ConnectionsView, run: Run, focus?: string): HTMLElement {
  const meta = CREDENTIAL_META[v.id];
  const slot = h('div.cx-slot');
  const actions = h('div.cx-actions');
  const showForm = () => {
    slot.replaceChildren(valueForm(v, run, () => slot.replaceChildren()));
  };
  if (meta.testable && v.source) {
    const test = h('button.btn', { type: 'button' }, '🧪 Test');
    test.addEventListener('click', () => {
      test.disabled = true;
      test.textContent = 'Testing…';
      void run(() => connectionsApi.test(v.id)).finally(() => ((test.disabled = false), (test.textContent = '🧪 Test')));
    });
    actions.append(test);
  }
  const pw = v.id === 'password';
  actions.append(h('button.btn', { type: 'button', class: v.source ? '' : 'primary', onclick: showForm }, pw ? '🔑 Change' : v.source === 'connections' ? '♻️ Replace' : v.source ? '⬇️ Save one here' : '➕ Add'));
  if (v.source === 'connections') {
    const remove = h('button.btn.danger', { type: 'button' }, pw ? 'Use the launcher’s again' : 'Remove');
    remove.addEventListener('click', () => {
      if (!confirm(pw ? 'Hand the password back to AGENT_OFFICE_PASSWORD / the generated one?' : `Remove the ${meta.label} from Connections? The office falls back to its environment variable or file, if there is one.`)) return;
      void run(() => connectionsApi.remove(v.id), `${meta.label} removed`);
    });
    actions.append(remove);
  }
  const card = h(
    'section.cx-card',
    { id: `cx-${v.id}`, class: `${v.status}${focus === v.id ? ' focus' : ''}` },
    h('div.cx-head', {}, h('span.cx-icon', { 'aria-hidden': 'true' }, meta.icon), h('h4', {}, meta.label), h('span.cx-status', { class: v.status }, STATUS[v.status])),
    h('p.cx-where', {}, where(v)),
    v.warning ? h('p.cx-warn', {}, `⚠️ ${v.warning}`) : null,
    lastTest(v),
    actions,
    slot,
    v.id === 'mendix' ? mendixFloors(view, run) : null,
    help(v, view.org),
  );
  if (focus === v.id && v.status === 'missing') showForm();
  return card;
}
